### ISSUE TITLE
More power

### ISSUE THREAD

**Issue by JamesZlosnik** [j3551ca/fluflo#2]
Hi Jess,

Just a suggestion to increase the available threads to the CPU demanding tasks such as Tree building.  It is currently quite slow on the server even with a small tree.  I can see from `squeue` that the tree building step is only using 2 threads.  32 threads should do it but it might be worth having a look at the reports to see where the bottlenecks are and assign as needed.

**Comment by j3551ca** [comment]
Thank you, James. Increased CPU limit for tree-generation process via ${task.cpus} in the process config scope.
